/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import Back.GestaoProjetos;
import static Back.GestaoProjetos.ser;
import Back.Projeto;
import Back.Utilizador;
import java.awt.Dimension;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class VisualizarProjetos extends javax.swing.JFrame {

    private GestaoProjetos dados;
    DefaultTableModel tProjetos;
    public static Utilizador sessao;
    public Utilizador u;
    
    public VisualizarProjetos(GestaoProjetos d, Utilizador r ) {
        initComponents();
        dados = d;
        u = r;
        
      
        
        tProjetos = (DefaultTableModel) TProjetos.getModel();
    
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TProjetos = new javax.swing.JTable();
        botaoVoltar = new javax.swing.JButton();
        addTarefas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TProjetos.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        TProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Descrição", "Data Inicio", "Data Fim", "Colaboradores", "Tarefas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TProjetos);

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        addTarefas.setText("Adicionar Tarefas");
        addTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTarefasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoVoltar)
                        .addGap(92, 92, 92)
                        .addComponent(addTarefas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar)
                    .addComponent(addTarefas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();

    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void addTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTarefasActionPerformed
          
        int escolha = TProjetos.getSelectedRow();
        if (TProjetos.getSelectionModel().isSelectionEmpty() == false) {
            CriarTarefas janela = null;
            String nome = (String) TProjetos.getValueAt(escolha, 0);
            String descricao = (String) TProjetos.getValueAt(escolha, 1);
            Date dataInicio = (Date) TProjetos.getValueAt(escolha, 2);
            Date dataFim = (Date) TProjetos.getValueAt(escolha, 3);
            
            for (Projeto elemento : Main.getDados().visualizarProjetos()) {
                if ((elemento.getNome().equals(nome)) 
                        && (elemento.getDescricao().equals(descricao)) 
                        && (elemento.getInicio().equals(dataInicio))
                        && (elemento.getFim().equals(dataFim))) {
                    
                    janela = new CriarTarefas(dados, elemento);
           
                }
            }
            //if(sessao.equals(Main.getDados().()){
            //System.out.println(Main.getDados().getProjeto(nome, Entrar.sessao.getEmail()));
            
            JFrame f = new JFrame();  
            Dimension d = new Dimension();
            d.setSize(598,501);
            f.setSize(d);
            janela.setVisible(true);
            f.add(janela);
            f.setVisible(true);
            }
            
       // } 
        else {
            JOptionPane.showMessageDialog(this, "Selecione um Projeto.");

        }
        
        
        
    }//GEN-LAST:event_addTarefasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main8(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TProjetos;
    private javax.swing.JButton addTarefas;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void guardar(String ser) {
        
    }
}
